/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 AirComp.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Shoes(props) {
  const { nodes, materials } = useGLTF("/AirComp.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.BackLeftAndRight.geometry}
        material={materials["default"]}

        position={[-4.38, 0.3, -0.01]}
        rotation={[0, 1.54, 0]}
        scale={8.34}
      />
      <mesh
        geometry={nodes.BackOftheShoes.geometry}
        material={materials["default"]}
        position={[-4.38, 0.3, -0.01]}
        rotation={[0, 1.54, 0]}
        scale={8.34}
      />
      <mesh
        geometry={nodes.BottomOfTheShoes.geometry}
        material={materials["default"]}
        position={[-4.38, 0.3, -0.01]}
        rotation={[0, 1.54, 0]}
        scale={8.34}
      />
      <mesh
        geometry={nodes.Laces.geometry}
        material={materials["default"]}
        position={[-4.42, 0.97, 0.72]}
        rotation={[-0.68, 1.53, 1.15]}
        scale={8.56}
      />
      <mesh
        geometry={nodes.Nike_Logo_right.geometry}
        material={materials["default"]}
        position={[-5.05, 0.83, -1.87]}
        rotation={[-Math.PI, 1.55, -Math.PI]}
        scale={8.38}
      />
      <mesh
        geometry={nodes.Shoe_Flap.geometry}
        material={materials["default"]}
        position={[-4.42, 0.52, -0.24]}
        rotation={[-2.09, 1.42, -0.94]}
        scale={-6.8}
      />
      <mesh
        geometry={nodes.TheEntireShoes.geometry}
        material={materials["default"]}
        position={[-4.38, 0.3, -0.01]}
        rotation={[0, 1.54, 0]}
        scale={8.34}
      />
      <mesh
        geometry={nodes.theFrontFromINside.geometry}
        material={materials["default"]}
        position={[-4.38, 0.3, -0.01]}
        rotation={[0, 1.54, 0]}
        scale={8.34}
      />
      <mesh
        geometry={nodes.TheFrontOfTheShoes.geometry}
        material={materials["default"]}
        position={[-4.38, 0.3, -0.01]}
        rotation={[0, 1.54, 0]}
        scale={8.34}
      />
      <mesh
        geometry={nodes.Ticket.geometry}
        material={materials["default"]}
        position={[-4.41, 0.21, -0.01]}
        rotation={[0, 1.51, 0]}
        scale={8.82}
      />
    </group>
  );
}

useGLTF.preload("/AirComp.glb");
